all:
	cd common && make
	cd features && make
	cd linalg && make
	cd LegsDetector && make

clean:
	cd common && make clean	
	cd features && make clean
	cd linalg && make clean
	cd LegsDetector && make clean
	rm -f *~
